name: 1vs1
main: Minifixio\onevsone\OneVsOne
version: 0.1.1
api: [3.0.0, 4.0.0]
description: 1vs1 Plugin
author: Minifixio edited by Zeao.
permissions:
  onevsone.refarena:
    description: "Allows using /refarena"
    default: op
