name: 1vs1
main: Minifixio\onevsone\OneVsOne
version: 2.0.0-BETA
api: [4.0.0]
description: 1vs1 Plugin
author: Minifixio, edited by Zeao, fixed by NickTehUnicorn.
permissions:
  onevsone.arena:
    description: "Allows using /arena"
    default: op
