---
# 1vs1 Config
# Plugin by Minifixio

###############
#1vs1 settings
config-version: "1.0.0"
## DO NOT TOUCH the config-version option, this is for internal use only, and editing it could result in you breaking the plugin.

###############
# Time limit for each duel, in minutes:
time-limit: 3

# TODO: Add Custom kits

# If you want to force the kits:
force-kit: true

# Keep Inventory

# Do you want to keep inventory turned on when a player dies in a 1vs1 match? - Currently experiamental.

keep-inventory: false

duel_items:
- "276, 0, 1"
- "310, 0, 1"
- "311, 0, 1"
- "312, 0, 1"
- "313, 0, 1"
## Items to duel with! Requires item numbers instead of item names, so for example, 276 would be a diamond sword.
## You can add as many items as you wish.
## To-Do add armor auto equip instead of manual equip on duel start.
...
